### ISSUE TITLE
KeyError 'datatype' when preprocessing the latest wikidata dump (as of April 16)

### ISSUE THREAD

**Issue by phucdoitoan** [neelguha/simple-wikidata-db#7]
Hi,

Thank you for the useful github code.

When I run the code in preprocess_dump.py to process the lastest wikidata dump (as of April 16) with 28 processes, I got the following error with processes 28. However, the code seems still running and produce processed tables.

Do you know if the error is something I should care about or I can just ignore it?

Thank you a lot!

`Process Process-28:
Traceback (most recent call last):
  File "**/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "**/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "**/simple-wikidata-db/simple_wikidata_db/preprocess_utils/worker_process.py", line 151, in process_data
    out_queue.put(process_json(ujson.loads(json_obj), language_id))
  File "**/simple-wikidata-db/simple_wikidata_db/preprocess_utils/worker_process.py", line 91, in process_json
    datatype = claim['mainsnak']['datatype']
KeyError: 'datatype'`

**Comment by neelguha** [comment]
I haven't gotten a chance to try and reproduce the error, but it looks like at least one of the claim objects doesn't have a `datatype` key. I haven't seen this error previously, so I wonder if it's something in most recent dump?

One small fix would be to disregard all claims which don't have a `datatype` key, and then count how many you drop (or write them to some error log file)?

**Comment by phucdoitoan** [comment]
Hi there,

Thanks a lot for your reply.
I do not know much about wikidta so I'm not sure `datatype` key is something recent.
I'll try your suggestion.
However, even with the error reported, it seems like the code works fine and all the output tables seem okie.

**Comment by jstzwj** [comment]
I encountered this error on the latest dump as well, KeyError 'datatype' appeared in obj['claims']. I tried to print these claims, and there were a total of 8 errors, as shown below:
```json
{
    "mainsnak": {
        "snaktype": "value",
        "property": "P7859",
        "datavalue": {
            "value": "lccn-no2008136488",
            "type": "string"
        }
    },
    "type": "statement",
    "id": "Q59114$3F4FD99E-3A57-4400-8A12-5EAD27F872E6",
    "rank": "normal",
    "references": [
        {
            "hash": "28566645c1933e3e0ba69ef684ec0dacb975ad74",
            "snaks": {
                "P214": [
                    {
                        "snaktype": "value",
                        "property": "P214",
                        "datavalue": {
                            "value": "138233708",
                            "type": "string"
                        },
                        "datatype": "external-id"
                    }
                ]
            },
            "snaks-order": [
                "P214"
            ]
        }
    ]
}
{
    "mainsnak": {
        "snaktype": "value",
        "property": "P7859",
        "datavalue": {
            "value": "lccn-n78020021",
            "type": "string"
        }
    },
    "type": "statement",
    "id": "Q7329609$88169939-5064-455C-AAAA-710DCBB24653",
    "rank": "normal",
    "references": [
        {
            "hash": "fd7025c9fc3be5ba8a8a1bac75405e131ca5bdb0",
            "snaks": {
                "P214": [
                    {
                        "snaktype": "value",
                        "property": "P214",
                        "datavalue": {
                            "value": "49278467",
                            "type": "string"
                        },
                        "datatype": "external-id"
                    }
                ]
            },
            "snaks-order": [
                "P214"
            ]
        }
    ]
}
{
    "mainsnak": {
        "snaktype": "value",
        "property": "P7859",
        "datavalue": {
            "value": "lccn-n2017075224",
            "type": "string"
        }
    },
    "type": "statement",
    "id": "Q84951097$2726637A-40C9-43F7-AC9C-9CE2722448DC",
    "rank": "normal",
    "references": [
        {
            "hash": "884892c90ca154633737b7788feb64a338acc370",
            "snaks": {
                "P214": [
                    {
                        "snaktype": "value",
                        "property": "P214",
                        "datavalue": {
                            "value": "260601859",
                            "type": "string"
                        },
                        "datatype": "external-id"
                    }
                ]
            },
            "snaks-order": [
                "P214"
            ]
        }
    ]
}
{
    "mainsnak": {
        "snaktype": "value",
        "property": "P7859",
        "datavalue": {
            "value": "lccn-n91076470",
            "type": "string"
        }
    },
    "type": "statement",
    "id": "Q5791629$36866452-FF15-4891-961E-CEECBAE07AEB",
    "rank": "normal",
    "references": [
        {
            "hash": "dd858a9ca9ab31c9c341206d5ed2f73c9bea881a",
            "snaks": {
                "P214": [
                    {
                        "snaktype": "value",
                        "property": "P214",
                        "datavalue": {
                            "value": "13951189",
                            "type": "string"
                        },
                        "datatype": "external-id"
                    }
                ]
            },
            "snaks-order": [
                "P214"
            ]
        }
    ]
}
{
    "mainsnak": {
        "snaktype": "value",
        "property": "P7859",
        "datavalue": {
            "value": "lccn-no2013053805",
            "type": "string"
        }
    },
    "type": "statement",
    "id": "Q2891155$5F764B85-03CE-4059-9292-ED16BBC335E2",
    "rank": "normal",
    "references": [
        {
            "hash": "275c20a671b7a63723ac958897a578e5b452fd1b",
            "snaks": {
                "P214": [
                    {
                        "snaktype": "value",
                        "property": "P214",
                        "datavalue": {
                            "value": "301200558",
                            "type": "string"
                        },
                        "datatype": "external-id"
                    }
                ]
            },
            "snaks-order": [
                "P214"
            ]
        }
    ]
}
{
    "mainsnak": {
        "snaktype": "value",
        "property": "P7859",
        "datavalue": {
            "value": "viaf-2608152331601603260003",
            "type": "string"
        }
    },
    "type": "statement",
    "id": "Q42699808$A8C5DDDB-27F1-43FD-A0D5-A8AFCCD38A45",
    "rank": "normal",
    "references": [
        {
            "hash": "ae9ed214f57d9a59a24f8e8132e0752f24694f02",
            "snaks": {
                "P214": [
                    {
                        "snaktype": "value",
                        "property": "P214",
                        "datavalue": {
                            "value": "2608152331601603260003",
                            "type": "string"
                        },
                        "datatype": "external-id"
                    }
                ]
            },
            "snaks-order": [
                "P214"
            ]
        }
    ]
}
{
    "mainsnak": {
        "snaktype": "value",
        "property": "P7859",
        "datavalue": {
            "value": "lccn-n99028187",
            "type": "string"
        }
    },
    "type": "statement",
    "id": "Q42699808$BC5B4111-9576-4199-A930-249395ED7590",
    "rank": "normal",
    "references": [
        {
            "hash": "4d520b05a5d17318792447f3cba6c64efbccf074",
            "snaks": {
                "P214": [
                    {
                        "snaktype": "value",
                        "property": "P214",
                        "datavalue": {
                            "value": "14943972",
                            "type": "string"
                        },
                        "datatype": "external-id"
                    }
                ]
            },
            "snaks-order": [
                "P214"
            ]
        }
    ]
}
{
    "mainsnak": {
        "snaktype": "value",
        "property": "P969",
        "datavalue": {
            "value": "Kadijk 1",
            "type": "string"
        }
    },
    "type": "statement",
    "id": "Q17446473$6ACF557D-1B18-4D05-ABE2-76E03298BAE9",
    "rank": "normal"
}
```
